SIE/urls.py
# SIE/urls.py
from django.contrib import admin
from django.urls import path, include
from signin import views as signin_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('sign-in/', include('signin.urls')),
    path('index/', include('index.urls')),
    path('anexo/', include('anexo.urls')),
    path('admin-signup/', include('signinAdmin.urls', namespace='signinAdmin')),
    path('encuesta/', include('encuesta.urls')),
    path('importador/', include('importador.urls')),
    path('anexoR/', include('anexoR.urls')),
    path('encuestaR/', include(('encuestaR.urls', 'encuestaR'), namespace='encuestaR')),
    
]

anexoR/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'anexoR'  # Esto define el namespace para las referencias en las plantillas

urlpatterns = [
    path('', views.viewAnexos, name='index'),
    path('A1/', views.viewA1, name='A1'),  # Agregamos name='A1'
    path('A2/', views.viewA2, name='A2'),  # Agregamos name='A2'
    path('A3/', views.viewA3, name='A3'),  # Agregamos name='A3'
    path('exportarA1/', views.exportarA1, name='exportarA1'),
    path('exportarA2/', views.exportarA2, name='exportarA2'),
    path('exportarA3/', views.exportarA3, name='exportarA3'),
    path('exportarA4/', views.exportarA4, name='exportarA4'),
    path('A4/', views.A4, name='A4'),
    path('exportar-anexo/', views.formulario_export_anexo, name='formulario_export_anexo'),
    path('exportar-anexo-por-carrera/', views.exportar_anexo_por_carrera, name='exportar_anexo_por_carrera'),
]

sie_backend/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/layouts/A1.html
{% extends "respuestasGrafico.html" %}
{% load static %}

{% block content %}

<!--TODO poner filtros-->


<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Tip', 'cantidad'],
            ['Titulados', {{ titulo.si }}],
    ['Sin titulo', {{ titulo.no }}],
            
        ]);

    var options = {
        title: 'ALUMNOS TITULADOS',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
    chart.draw(data, options);
    }
</script>

<div>
    <div class="question-group">
        <div id="donutchart" style="width: 100%; height: 500px;"></div>
    </div>
    
</div>


{% endblock %}

templates/layouts/A2.html
{% extends "respuestasGrafico.html" %}
{% load static %}

{% block content %}


<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Trabaja', 'cantidad'],
            ['Trabajan', {{ trabaja.si }}],
    ['No trabajan', {{ trabaja.no }}],
            
        ]);

    var options = {
        title: 'EGRESADOS CON TRABAJO',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartTrabaja'));
    chart.draw(data, options);
    }
</script>
<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Relacion', 'cantidad'],
            ['Si', {{ relacion.si }}],
    ['No ', {{ relacion.no }}],
            
        ]);

    var options = {
        title: 'RELACION DEL TRABAJO Y SU CARRERA',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartRelacion'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['bar'] });
    google.charts.setOnLoadCallback(drawStuff);

    function drawStuff() {
        var data = new google.visualization.arrayToDataTable([
            ['Antigüedad', 'cantidad'],
            ["0-3 Meses", {{antiguedad.uno}}],
            ["4-6 Meses", {{antiguedad.dos}}],
            ["6 Meses", {{antiguedad.tres}}],
            ["Más de 1 año", {{antiguedad.cuatro}}],
        ]);

        var options = {
            title: 'Antigüedad en el trabajo',
            width: 1155,
            legend: { position: 'none' },
            chart: {
                title: 'ANTIGÜEDAD EN EL TRABAJO DE LOS EGRESADOS',
                subtitle: 'Cuanto tiempo llevan trabajando'
            },
            bars: 'horizontal', // Required for Material Bar Charts.
            axes: {
                x: {
                    0: { side: 'top', label: 'Cantidad' } // Top x-axis.
                }
            },
            bar: { groupWidth: "100%" }
        };

        var chart = new google.charts.Bar(document.getElementById('top_x_div'));
        chart.draw(data, options);
    };
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Trabaja', 'cantidad'],
            ['Ya lo tenian', {{ trabajoT.uno }}],
            ['Menos de 6 meses', {{ trabajoT.dos }}],
            ['Más de 1 año', {{ trabajoT.tres }}],
            
        ]);

    var options = {
        title: 'TIEMPO EN EL QUE LOS EGRESADOS CONSIGUIERON TRABAJOS RELACIONADOS A SU CARRERA',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartTiempoRelacionado'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Sector', 'cantidad'],
            ['Privado', {{ sector.uno }}],
            ['Publico', {{ sector.dos }}],
            ['Empresa propia', {{ sector.tres }}],
            ['Otro', {{ sector.cuatro }}],
            
        ]);

    var options = {
        title: 'SECTOR EN EL QUE TRABAJAN LOS EGRESADOS',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartTiempoSector'));
    chart.draw(data, options);
    }
</script>



<script type="text/javascript">
    google.charts.load('current', { 'packages': ['bar'] });
    google.charts.setOnLoadCallback(drawStuff);

    function drawStuff() {
        var data = new google.visualization.arrayToDataTable([
            ['Rol', 'cantidad'],
            ["Director", {{puesto.uno}}],
            ["Jefe", {{puesto.dos}}],
            ["Supervisor", {{puesto.tres}}],
            ["Coordinador", {{puesto.cuatro}}],
            ["Empleado", {{puesto.cinco}}],
            ["Dueño", {{puesto.seis}}],
            ["Otro", {{puesto.siete}}],
        ]);

        var options = {
            title: 'Antigüedad en el trabajo',
            width: 1111,
            legend: { position: 'none' },
            chart: {
                title: 'ROL DE DESEMPEÑO DE LOS EGRESADO',
                subtitle: ''
            },
            bars: 'horizontal', // Required for Material Bar Charts.
            axes: {
                x: {
                    0: { side: 'top', label: 'Cantidad' } // Top x-axis.
                }
            },
            bar: { groupWidth: "100%" }
        };

        var chart = new google.charts.Bar(document.getElementById('barrasRol'));
        chart.draw(data, options);
    };
</script>

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['bar'] });
    google.charts.setOnLoadCallback(drawStuff);

    function drawStuff() {
        var data = new google.visualization.arrayToDataTable([
            ['Area', 'cantidad'],
            ["Director", {{puesto.uno}}],
            ["Jefe", {{puesto.dos}}],
            ["Supervisor", {{puesto.tres}}],
            ["Coordinador", {{puesto.cuatro}}],
            ["Empleado", {{puesto.cinco}}],
            ["Dueño", {{puesto.seis}}],
            ["Otro", {{puesto.siete}}],
        ]);

        var options = {
            title: 'AREA DE DESEMPEÑO DE LOS EGRESADO ',
            width: 1155,
            legend: { position: 'none' },
            chart: {
                title: 'AREA DE DESEMPEÑO DE LOS EGRESADO',
                subtitle: ''
            },
            bars: 'horizontal', // Required for Material Bar Charts.
            axes: {
                x: {
                    0: { side: 'top', label: 'Cantidad' } // Top x-axis.
                }
            },
            bar: { groupWidth: "100%" }
        };

        var chart = new google.charts.Bar(document.getElementById('barrasArea'));
        chart.draw(data, options);
    };
</script>

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['bar'] });
    google.charts.setOnLoadCallback(drawStuff);

    function drawStuff() {
        var data = new google.visualization.arrayToDataTable([
            ['Medio', 'cantidad'],
            ["Bolsa de trabajó del TecNM/ITVer ", {{medio.uno}}],
            ["Anuncio en internet", {{medio.dos}}],
            ["Recomendación de colegas", {{medio.tres}}],
            ["Residencias profesional", {{medio.cuatro}}],
            ["Otras", {{medio.cinco}}],
            
        ]);

        var options = {
            title: 'MEDIO DE POR EL CUAL EL EGRESADO ENCONTRÓ TRABAJO ',
            width: 1155,
            legend: { position: 'none' },
            chart: {
                title: 'MEDIO DE POR EL CUAL EL EGRESADO ENCONTRÓ TRABAJO ',
                subtitle: ''
            },
            bars: 'horizontal', // Required for Material Bar Charts.
            axes: {
                x: {
                    0: { side: 'top', label: 'Cantidad' } // Top x-axis.
                }
            },
            bar: { groupWidth: "100%" }
        };

        var chart = new google.charts.Bar(document.getElementById('barrasMedio'));
        chart.draw(data, options);
    };
</script>


<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Sector', 'cantidad'],
            [' Muy satisfecho  ', {{ satisfaccion.uno }}],
            ['Satisfecho', {{ satisfaccion.dos }}],
            ['Poco satisfecho', {{ satisfaccion.tres }}],
            ['Insatisfecho', {{ satisfaccion.cuatro }}],
            
        ]);

    var options = {
        title: 'SATISFACCION DE LOS EGRESADOS EN SU TRABAJO',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartSatisfaccion'));
    chart.draw(data, options);
    }
</script>

<div class="question-group">
    <div id="donutchartTrabaja" style="width: 100%; height: 500px;"></div>
    <div id="donutchartRelacion" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="top_x_div" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="donutchartTiempoRelacionado" style="width: 100%; height: 500px;"></div>
    <div id="donutchartTiempoSector" style="width: 100%; height: 500px;"></div>
    
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="barrasRol" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="barrasArea" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="barrasMedio" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="donutchartSatisfaccion" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="barrasArea" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="form-section">
    <a href="{% url 'anexoR:exportarA2' %}" class="button">Descargar CSV A2</a>
</div>


{% endblock %}

templates/layouts/A3.html
{% extends "respuestasGrafico.html" %}
{% load static %}

{% block content %}

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['bar'] });
    google.charts.setOnLoadCallback(drawStuff);

    function drawStuff() {
        var data = new google.visualization.arrayToDataTable([
            ['Contenido', 'cantidad'],
            [" Manejo de softwares ", {{ reforzar.uno }}],
    ["Manejo de Normas Nacionales e Internacionales", {{ reforzar.dos }}],
        ["Evaluación de proyectos de inversión", {{ reforzar.tres }}],
        ["Habilidades directivas", {{ reforzar.cuatro }}],
        ["Otras", {{ reforzar.cinco }}],
        ]);

    var options = {
        title: 'Antigüedad en el trabajo',
        width: 1111,
        legend: { position: 'none' },
        chart: {
            title: 'LOS EGRESADOS SUGIEREN REFORZAR ',
            subtitle: 'Reforzar o actualizar contenidos del programa educativo'
        },
        bars: 'horizontal', // Required for Material Bar Charts.
        axes: {
            x: {
                0: { side: 'top', label: 'Cantidad' } // Top x-axis.
            }
        },
        bar: { groupWidth: "100%" }
    };

    var chart = new google.charts.Bar(document.getElementById('top_x_div'));
    chart.draw(data, options);
    };
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Sector', 'cantidad'],
            ['Totalmente', {{ competencias.uno }}],
    ['Suficiente', {{ competencias.dos }}],
        ['Poco', {{ competencias.tres }}],
        ['Nada', {{ competencias.cuatro }}],
            
        ]);

    var options = {
        title: 'LO QUE LOS EGRESADOS CONSIDERAN SOBRE LA AYUDA DE LAS COMPETENCIAS ADQUIRIDAS EN LA INSTITUCIÓN FRENTE A SU TRABAJO',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartCompetencia'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Sector', 'cantidad'],
            [' Muy satisfecho  ', {{ satisfaccion.uno }}],
    ['Satisfecho', {{ satisfaccion.dos }}],
        ['Poco satisfecho', {{ satisfaccion.tres }}],
        ['Insatisfecho', {{ satisfaccion.cuatro }}],
        ]);

    var options = {
        title: 'SATISFACCION DE LOS EGRESADOS EN SU TRABAJO',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartSatisfaccion'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Contacto', 'cantidad'],
            ['Si', {{ contacto.si }}],
    ['No ', {{ contacto.no }}],
            
        ]);

    var options = {
        title: 'EGRESADOS A LOS QUE LA INSTITUCIÓN A CONTACTADO',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartContacto'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Participación', 'cantidad'],
            ['Si', {{ participar.si }}],
    ['No ', {{ participar.no }}],
            
        ]);

    var options = {
        title: 'EGRESADOS INTERESADOS EN PARTICIPAR CON LA INSTITUCIÓN',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartParticipar'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['bar'] });
    google.charts.setOnLoadCallback(drawStuff);

    function drawStuff() {
        var data = new google.visualization.arrayToDataTable([
        ['Rol', 'cantidad'],
        ["Curso o conferencia", {{ aporte.uno }}],
        ["Visita industrial ", {{ aporte.dos }}],
        ["Realización de Residencias", {{ aporte.tres }}],
        ["Realizar investigaciones", {{ aporte.cuatro }}],
        ["Educación Dual", {{ aporte.cinco }}],
        ["Donativos en especie", {{ aporte.seis }}],
        ["Otro", {{ aporte.siete }}],
        ]);

    var options = {
        title: 'En que están dispuestos a participar',
        width: 1155,
        legend: { position: 'none' },
        chart: {
            title: 'EN QUE ESTÁN DISPUESTOS A PARTICIPAR',
            subtitle: ''
        },
        bars: 'horizontal', // Required for Material Bar Charts.
        axes: {
            x: {
                0: { side: 'top', label: 'Cantidad' } // Top x-axis.
            }
        },
        bar: { groupWidth: "100%" }
    };

    var chart = new google.charts.Bar(document.getElementById('barrasParticipar'));
    chart.draw(data, options);
    };
</script>


<div class="question-group" style="margin-top: 25px;">
    <div id="donutchartCompetencia" style="width: 100%; height: 500px;"></div>
    <div id="donutchartSatisfaccion" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="top_x_div" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="donutchartContacto" style="width: 100%; height: 500px;"></div>
    <div id="donutchartParticipar" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="barrasParticipar" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="form-section">
    <a href="{% url 'anexoR:exportarA3' %}" class="button">Descargar CSV A3</a>
</div>

{% endblock %}

templates/layouts/E1.html
{% extends "respuestasGrafico.html" %}
{% load static %}

{% block content %}


<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Sexo', 'cantidad'],
            ['Femenino', {{ sexo.si }}],
    ['Masculino', {{ sexo.no }}],
            
        ]);

    var options = {
        title: 'PORCENTAJE DEL SEXO DE LOS EGRESADOS',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartSexo'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Estado', 'cantidad'],
            ['Soltero', {{ estado.si }}],
    ['Casado', {{ estado.no }}],
            
        ]);

    var options = {
        title: 'ESTADO CIVIL DE LOS EGRESADOS',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartEstado'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Titulado', 'cantidad'],
            ['Si', {{ titulado.si }}],
    ['NO', {{ titulado.no }}],
            
        ]);

    var options = {
        title: 'TITULO DE LOS EGRESADOS',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartTitulo'));
    chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['Paquetes', 'cantidad'],
            ['Si', {{ paquetes.si }}],
    ['NO', {{ paquetes.no }}],
            
        ]);

    var options = {
        title: 'MANEJO DE PAQUETES COMPUTACIONALES DE LOS EGRESADOS',
        pieHole: 0.4,
    };

    var chart = new google.visualization.PieChart(document.getElementById('donutchartPaquetes'));
    chart.draw(data, options);
    }
</script>

<div class="question-group">
    <div id="donutchartSexo" style="width: 100%; height: 500px;"></div>
    <div id="donutchartEstado" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<div class="question-group" style="margin-top: 25px;">
    <div id="donutchartTitulo" style="width: 100%; height: 500px;"></div>
    <div id="donutchartPaquetes" style="width: 100%; height: 500px;"></div>
</div>
<hr>
<h2>

</h2>
{% endblock %}

templates/layouts/E5.html
{% extends "respuestasGrafico.html" %}
{% load static %}
{% block content %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
google.charts.load("current", {packages:["corechart"]});
google.charts.setOnLoadCallback(drawCharts);

function drawCharts() {
    drawChart('cursosActualizacion_chart', '¿Tomó cursos de actualización?', {{ cursosActualizacion|safe }});
    drawChart('tomarPosgrado_chart', '¿Desea cursar posgrado?', {{ tomarPosgrado|safe }});
    drawChart('orgSociales_chart', '¿Pertenece a organizaciones sociales?', {{ orgSociales|safe }});
    drawChart('orgProfesionales_chart', '¿Pertenece a organismos profesionales?', {{ orgProfesionales|safe }});
    drawChart('asociacionEgresados_chart', '¿Pertenece a asociación de egresados?', {{ asociacionEgresados|safe }});
}

function drawChart(divId, title, dataDict) {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Respuesta');
    data.addColumn('number', 'Cantidad');
    for (const [key, value] of Object.entries(dataDict)) {
        data.addRow([key, value]);
    }
    var options = {
        title: title,
        pieHole: 0.4,
        width: 600,
        height: 400
    };
    var chart = new google.visualization.PieChart(document.getElementById(divId));
    chart.draw(data, options);
}
</script>

<h2>Encuesta - Participación y Actualización (E5)</h2>
<div class="question-group" style="margin-top: 25px;">
    <div id="cursosActualizacion_chart"></div>
    <div id="tomarPosgrado_chart"></div>
</div>
<div class="question-group" style="margin-top: 25px;">
    <div id="orgSociales_chart"></div>
    <div id="orgProfesionales_chart"></div>
</div>
<div class="question-group" style="margin-top: 25px;">
    <div id="asociacionEgresados_chart"></div>
</div>

{% endblock %}